# Site
repository: martinfullstackdevsap/main
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Martin Mikus
title: Senior SAP Full-Stack Developer
email: martinmikus2@protonmail.com
phone: +420 601 531 976
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: martin-k-881394119
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Welcome to my professional work profile.
  My name is Martin, and I am a Full-Stack SAP Developer. I work daily with <mark>ABAP</mark> <mark>SAPUI5 / SAP Fiori</mark> <mark>JavaScript</mark> and <mark>SAP Business Workflow</mark>. 
  I am also familiar with building of <mark>oData</mark> services <mark>REST</mark> APIs <mark>CDS</mark> views and <mark>SOAP</mark> services.
  
  Mostly I work in <mark>SAP S/4HANA</mark> environment but also have experience with older ERP releases. 
  Primarily in modules <mark>FI-CO</mark>, <mark>HR/HCM</mark>, <mark>SD</mark>, <mark>MM</mark>, and <mark>BW</mark>.  

  For development, I use <mark>Eclipse ADT</mark> and <mark>SAP Business Application Studio</mark> and sometimes <mark>VS Code</mark>. 
  I am proficient in utilizing <mark>Git</mark> for source code management and team collaboration.

  Apart from project development, I support business as usual—analyzing errors, fixing bugs, and designing new business solutions. 
  I have successfully delivered multiple projects for European and Asian customers.
  In my projects section, I’ve highlighted the most significant ones—those where development took longer than two months.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Magellan Tax Portal
        sub_title: Heidelberg Materials, Germany
        caption: Duration - 1 year (2024-2025)
        description: | # this will include new lines to allow paragraphs
          I participated on development of Tax Portal as technical team leader. I designed and developed UI of final solution using custom <mark>SAPUI5</mark> SDK.
          I developed core <mark>ABAP</mark> application classes,  tax calculations and logic in <mark>BW</mark>. I designed and builded <mark>oData</mark> services for data consumption.
          I used <mark>Git</mark> for collaboration between team members and <mark>SAP Business Application Studio</mark> for UI development.
      - layout: left
        title: Purchase Order, Purchase Requistion
        sub_title: Home Credit, Kazakhstan
        caption: Duration - 2 months (2025)
        description: | # this will include new lines to allow paragraphs
          I designed and developed custom <mark>SAP Business Workflow</mark> for Purchase Order and Purchase Requisition with dynamic approvers selections.
          Workflow templates were based on custom BOR object with inheritance of standard object.
          I modified standard transactions screens with user exits where I defined and created new custom fields with prepopulation logic. 
          In the end I integrated these two workflows inside <mark>My Inbox</mark> , created overview GUI report and handled user roles and authorizations.
      - layout: left
        title: SAP e-shop TETA
        sub_title: p.k.Solvent s.r.o., Czech Republic
        caption: Duration - 1 year 6 months (2023-2024)
        description: | # this will include new lines to allow paragraphs
          I developed a complete backend solution for e-shop www.teta.cz . For communication between e-shop and SAP I builded Swagger <mark>REST</mark> API to provide and consume data.
          With the retrieved data in <mark>ABAP</mark> I developed core logic to create purchase orders, invoices, deliveries, reservations, stocks, WM movements and other related objects.
          I developed <mark>SAPUI5</mark> custom applications for warehouse stock administration registered them into <mark>Fiori</mark> Launchpad with own <mark>oData</mark> services.
          A barcode scanner application, which ran on mobile was part of development to support warehouse workers in packaging.
          In the end I integrated third-party <mark>REST</mark> API Balikomat to automatically create package labels, print labels, and register of packages for delivery service providers.
      - layout: left
        title: Asset Management
        sub_title: Home Credit, Kazakhstan
        caption: Duration - 3 months (2024)
        description: | # this will include new lines to allow paragraphs
          I took care about development of custom Asset Management <mark>SAPUI5</mark> applications for administration of company assets. I developed <mark>ABAP</mark>
          application classes that provided data to custom <mark>oData</mark> services. To handle asset transfer approval between employees I designed and developed custom
          class based <mark>SAP Business Workflow</mark> and developed custom My Inbox approval screens. In the end of project I created user roles with relevant authorizations and registered application
          into <mark>Fiori</mark> Launchpad.
      - layout: left
        title: Bizzi REST Integration
        sub_title: Home Credit, Vietnam
        caption: Duration - 4 months (2024)
        description: | # this will include new lines to allow paragraphs
          I participated on integration of third-party <mark>REST</mark> API into SAP. The project consisted of application <mark>ABAP</mark> classes with logic to create,
          update and delete of invoices, purchases orders, good receipts and travel receipts. Application classes handled inbound and outbound communication between SAP and third-party external system Bizzi.
      - layout: left
        title: Payment Request Invoices
        sub_title: Home Credit, Philippines
        caption: Duration - 4 months (2023)
        description: | # this will include new lines to allow paragraphs
          I designed and developed two custom <mark>SAPUI5</mark> applications to create invoices from payment requests. First application was to create payment request from scratch where used master-detail <mark>Fiori</mark> template. Second application was
          builded for administrators where I used worklist <mark>Fiori</mark> template with detail navigation. Third application was based on worklist <mark>Fiori</mark> template. For all applications I builded <mark>oData</mark> services.
          With requested data I created <mark>ABAP</mark> application class to handle data validations, data storage and invoice creation. As requested data had to
          be approved I created <mark>SAP Business Workflow</mark> and integrated custom <mark>My Inbox</mark> UI approval screen.
      - layout: left
        title: Training Management
        sub_title: Home Credit, Indonesia
        caption: Duration - 4 months (2023)
        description: | # this will include new lines to allow paragraphs
          I designed and developed three custom <mark>SAPUI5</mark> applications to handle user training registration, administration and reporting. Application for registration was created using <mark>Fiori</mark> master-detail template. 
          Application for administrators to update training lists, participants results and indicators was created by combination of custom <mark>SAPUI5</mark> SDK and third-party library jspreadsheet https://bossanova.uk/jspreadsheet/ . 
          For data consumption I builded <mark>oData</mark> services. Backend logic was supported by <mark>ABAP</mark> application classes where I handled validations, application data storage and HR infotype update. All applications were
          registered into <mark>Fiori</mark> Launchpad.
      - layout: left
        title: SAP Web Dynpro Migration
        sub_title: Home Credit, China
        caption: Duration - 1 year (2022)
        description: | # this will include new lines to allow paragraphs
          During the migration of Web Dynpro applications into <mark>Fiori</mark> Launchpad I developed 8 applications from the scratch using custom <mark>SAPUI5</mark> SDK, <mark>JavaScript</mark> and <mark>SAP Business Workflow</mark> . For each application
          I had to enhance approval tasks in workflow templates to align with <mark>My Inbox</mark> application. For every application I builded <mark>oData</mark> service for CRUD operations.
      - layout: left
        title: My Inbox SD,PP Workflows
        sub_title: Heidelberg Materials, Germany
        caption: Duration - 8 months (2021-2022)
        description: | # this will include new lines to allow paragraphs
          I developed cluster tables for customizing of conditions when <mark>SAP Business Workflow</mark> for Contract (SD), Bill of Materials (PP), Out of Tolerance (PP) should be triggered. I builded interfaces, <mark>ABAP</mark> application classes
          to handle triggering of workflow. I created custom BOR object for Contract (SD) with standard BOR inheritance and extended with functionality. For Bill of Materials (PP) and Out of Tolerance (PP) I created class based workflows.
          For every workflow I created template with approval tasks for My Inbox. In the end I developed framework to dynamically replace UI approval screen in <mark>My Inbox</mark> with standard <mark>Fiori</mark> extensibility 
          tools in <mark>SAP Business Application Studio</mark> . UI applications were stored in <mark>Git</mark> repositories.
      - layout: left
        title: My Travel Request V2
        sub_title: Home Credit, Philippines
        caption: Duration - 5 months (2020)
        description: | # this will include new lines to allow paragraphs
          I participated on development of <mark>SAP Business Workflow</mark> for <mark>Fiori</mark> applications Travel Request V2 and Travel Expense V2. I builded custom BOR objects with inheritance to standard object and designed and developed workflow templates.
          Workflow template was robust because it consisted of 9 levels of approvers based on multiple conditions like cost center, budget and other parameters. Workflow template logic was supported by application <mark>ABAP</mark> classes. In UI part I had to extend
          standard <mark>Fiori</mark> applications using standard extensibility concept in <mark>SAP WebIDE</mark>. For workflow approval I created custom UI approval screens in <mark>My Inbox</mark>. In the end I created user roles, assigned authorizations and registered
          applications into <mark>Fiori</mark> Launchpad.
      - layout: left
        title: USSPA Service Orders Planner
        sub_title: Versino CZ, s.r.o., Czech Republic
        caption: Duration - 4 months (2020)
        description: | # this will include new lines to allow paragraphs
          I designed and developed custom <mark>SAPUI5</mark> application for planning of services. Application consisted of interactive map with tags, list of orders and calendar. Apart from <mark>SAPUI5</mark> SDK I used custom <mark>JavaScript</mark> to meet
          customer requirements.
      - layout: left
        title: Trip Logbook
        sub_title: DHL Information Services s.r.o., Czech Republic
        caption: Duration - 4 months (2018)
        description: | # this will include new lines to allow paragraphs
          As a fulltime employee I developed custom master-detail <mark>Fiori</mark> application.The purpose of application was to manage company car bookings and track journey details. Application UI layout was changing dynamically based on customizing in SAP.
          Application was assigned to users in <mark>Fiori</mark> Launchpad.
      - layout: left
        title: Company Website www.consit.cz
        sub_title: CONSIT s.r.o., Czech Republic
        caption: Duration - 4 months (2018)
        description: | # this will include new lines to allow paragraphs
          As a fulltime employee I developed company website using <mark>HTML</mark> <mark>JavaScript</mark> with content CMS integration of https://www.couchcms.com/ .
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: EmbedIT s.r.o., Czech Republic
        link: https://www.embedit.com
        sub_title: Senior SAP Software Engineer
        caption: February 2019 - Present
        description: | # this will include new lines to allow paragraphs
            As SAP software engineer I design and develop business solutions for end customers. The biggest projects included development in <mark>ABAP</mark> <mark>SAPUI5</mark> and <mark>SAP Business Workflow</mark> .
      - layout: left
        title: Heidelberg Materials, Germany
        link: https://www.heidelbergmaterials.com
        sub_title: Senior SAP Software Engineer
        caption: September 2021 - Present
        description: | # this will include new lines to allow paragraphs
           I deliver software solutions for german customer. Mostly in are of <mark>SAP Business Workflow</mark> , custom <mark>ABAP</mark> business logic and <mark>Fiori</mark> applications development.
      - layout: left
        title: DHL Information Services s.r.o., Czech Republic
        link: https://group.dhl.com/
        sub_title: SAP Software Engineer
        caption: February 2018 - January 2019
        description: | # this will include new lines to allow paragraphs
           As full-time employee I supported business as usual. Fixing of issues, enhancements of existing solutions and development of new applications using <mark>SAPUI5</mark> SDK and <mark>ABAP</mark> . I had
           chance to travel to Kuala Lumpur, Malaysia to train developers in area of <mark>Fiori</mark> and <mark>SAPUI5</mark> .    
      - layout: left
        title: CONSIT s.r.o., Czech Republic
        link: https://www.consit.cz
        sub_title: SAP Fiori FrontEnd Developer
        caption: June 2016 - January 2018
        description: | # this will include new lines to allow paragraphs
           As full-time employee I designed and developed internal HR applications for company employees. I worked with <mark>SAPUI5</mark> SDK  <mark>JavaScript</mark> and <mark>ABAP</mark> . I developed company website.
           In this company I had opportunity to meet SAP for the first time.
      - layout: left
        title: Freelance Webdeveloper
        sub_title: Freelance Webdeveloper
        caption: January 2016 - May 2016
        description: | # this will include new lines to allow paragraphs
           I started my career as webmaster and webdeveloper. I got familiar with <mark>HTML</mark> <mark>JavaScript</mark> and <mark>Adobe Photoshop</mark> . Apart from small tasks for multiple websites 
           during this time I developed my very first website www.strednyliptov.sk .       
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Žilina in Žilina
        caption: 2010 - 2015
        sub_title: Services in IT
        description: | # this will include new lines to allow paragraphs
           I successfully graduated with a degree and wrote a thesis on securing web forms in <mark>PHP</mark> .
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
           I love to spend with my family. I am casual PS5 / PC gamer. I love to read books and improve myself in every possible way.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
