# Site
repository: martinfullstackdevsap/main
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Martin Mikus
title: Senior SAP Full Stack Developer
email: martinmikus2@protonmail.com
phone: +420 601 531 976
location: Prague, Czech Republic
#website: 

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: martin-k-881394119
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: another link
    icon: fab fa-twitter
    url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-5XZ478HH"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Welcome to my professional work profile.
  My name is Martin, and I am a Full Stack SAP Developer. I work daily with <mark>ABAP</mark> <mark>SAPUI5</mark> <mark>Fiori</mark> <mark>JavaScript</mark> and <mark>SAP Business Workflow</mark>. 
  I am proficient in building of <mark>oData</mark> services <mark>REST</mark> APIs <mark>CDS</mark> views and <mark>SOAP</mark> services.
  
  Mostly I work in <mark>SAP S/4HANA</mark> environment but also have experience with older SAP ERP releases.
  Primarily in modules <mark>FI-CO</mark>, <mark>HR/HCM</mark>, <mark>SD</mark>, <mark>MM</mark>, and <mark>BW</mark>.  

  For development, I use <mark>Eclipse ADT</mark> and <mark>SAP Business Application Studio</mark> and sometimes <mark>VS Code</mark>. 
  I am proficient in utilizing <mark>Git</mark> for source code management and team collaboration.

  Apart from project development, I support business as usual—analyzing errors, fixing bugs, and designing new business solutions. 
  I have successfully delivered multiple projects for European and Asian customers.
  In my projects section, I’ve highlighted the most significant ones—those where development took longer than two months.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Magellan Tax Portal
        sub_title: Heidelberg Materials, Germany
        caption: Duration - 1 year (2024-2025)
        description: | # this will include new lines to allow paragraphs
          I participated in the development of the Tax Portal as a technical team leader. 
          I designed and developed the UI of the final solution using the custom <mark>SAPUI5</mark> SDK. 
          I developed core <mark>ABAP</mark> application classes, tax calculations, and logic in <mark>BW</mark>. 
          I designed and built <mark>oData</mark> services for data consumption. 
          I used <mark>Git</mark> for collaboration between team members and <mark>SAP Business Application Studio</mark> for UI development.
      - layout: left
        title: Purchase Order, Purchase Requisition
        sub_title: Home Credit, Kazakhstan
        caption: Duration - 2 months (2025)
        description: | # this will include new lines to allow paragraphs
          I designed and developed a custom <mark>SAP Business Workflow</mark> for Purchase Order and Purchase Requisition with dynamic approver selections. 
          Workflow templates were based on a custom BOR object with inheritance from the standard object. 
          I modified standard transaction screens with user exits where I defined and created new custom fields with prepopulation logic. 
          In the end, I integrated these two workflows inside <mark>My Inbox</mark>, created an overview GUI report, and handled user roles and authorizations.
      - layout: left
        title: SAP e-shop TETA
        sub_title: p.k.Solvent s.r.o., Czech Republic
        caption: Duration - 1 year 6 months (2023-2024)
        description: | # this will include new lines to allow paragraphs
          I developed a complete backend solution for the e-shop www.teta.cz .
          For communication between the e-shop and SAP, I built a Swagger <mark>REST</mark> API to provide and consume data. 
          With the retrieved data in <mark>ABAP</mark>, I developed core logic to create purchase orders, invoices, deliveries, reservations, stocks, WM movements, and other related objects. 
          I developed <mark>SAPUI5</mark> custom applications for warehouse stock administration and registered them into the <mark>Fiori</mark> Launchpad with my own <mark>oData</mark> services. 
          A barcode scanner application, which ran on mobile, was part of the development to support warehouse workers in packaging. 
          In the end, I integrated the third-party <mark>REST</mark> API Balikomat to automatically create package labels, print labels, and register packages for delivery service providers.
      - layout: left
        title: Asset Management
        sub_title: Home Credit, Kazakhstan
        caption: Duration - 3 months (2024)
        description: | # this will include new lines to allow paragraphs
          I took care of the development of custom Asset Management <mark>SAPUI5</mark> applications for the administration of company assets. 
          I developed <mark>ABAP</mark> application classes that provided data to custom <mark>oData</mark> services. 
          To handle asset transfer approval between employees, I designed and developed a custom class-based <mark>SAP Business Workflow</mark> and developed custom My Inbox approval screens. 
          At the end of the project, I created user roles with relevant authorizations and registered the application into the <mark>Fiori</mark> Launchpad.
      - layout: left
        title: Bizzi REST Integration
        sub_title: Home Credit, Vietnam
        caption: Duration - 4 months (2024)
        description: | # this will include new lines to allow paragraphs
          I participated in the integration of a third-party <mark>REST</mark> API into SAP. 
          The project consisted of application <mark>ABAP</mark> classes with logic to create, update, and delete invoices, purchase orders, goods receipts, and travel receipts. 
          Application classes handled inbound and outbound communication between SAP and the third-party external system Bizzi.
      - layout: left
        title: Payment Request Invoices
        sub_title: Home Credit, Philippines
        caption: Duration - 4 months (2023)
        description: | # this will include new lines to allow paragraphs
          I designed and developed two custom <mark>SAPUI5</mark> applications to create invoices from payment requests. 
          The first application was to create payment requests from scratch using the master-detail <mark>Fiori</mark> template. 
          The second application was built for administrators using the worklist <mark>Fiori</mark> template with detail navigation. 
          The third application was based on the worklist <mark>Fiori</mark> template. 
          For all applications, I built <mark>oData</mark> services. 
          With the requested data, I created an <mark>ABAP</mark> application class to handle data validations, data storage, and invoice creation. 
          As the requested data had to be approved, I created an <mark>SAP Business Workflow</mark> and integrated a custom <mark>My Inbox</mark> UI approval screen.
      - layout: left
        title: Training Management
        sub_title: Home Credit, Indonesia
        caption: Duration - 4 months (2023)
        description: | # this will include new lines to allow paragraphs
          I designed and developed three custom <mark>SAPUI5</mark> applications to handle user training registration, administration, and reporting. 
          The application for registration was created using the <mark>Fiori</mark> master-detail template. 
          The application for administrators to update training lists, participants' results, and indicators was created by combining the custom <mark>SAPUI5</mark> SDK and the third-party library jspreadsheet (https://bossanova.uk/jspreadsheet/). 
          For data consumption, I built <mark>oData</mark> services. 
          The backend logic was supported by <mark>ABAP</mark> application classes where I handled validations, application data storage, and HR infotype updates. 
          All applications were registered into the <mark>Fiori</mark> Launchpad.
      - layout: left
        title: SAP Web Dynpro Migration
        sub_title: Home Credit, China
        caption: Duration - 1 year (2022)
        description: | # this will include new lines to allow paragraphs
          During the migration of Web Dynpro applications into <mark>Fiori</mark> Launchpad, I developed 8 applications from scratch using custom <mark>SAPUI5</mark> SDK, <mark>JavaScript</mark>, 
          and <mark>SAP Business Workflow</mark>. For each application, I had to enhance approval tasks in workflow templates to align with the <mark>My Inbox</mark> application. 
          For every application, I built <mark>oData</mark> services for CRUD operations.
      - layout: left
        title: My Inbox SD,PP Workflows
        sub_title: Heidelberg Materials, Germany
        caption: Duration - 8 months (2021-2022)
        description: | # this will include new lines to allow paragraphs
          I developed cluster tables for customizing conditions when <mark>SAP Business Workflow</mark> for Contract (SD), Bill of Materials (PP), Out of Tolerance (PP) should be triggered. 
          I built interfaces, <mark>ABAP</mark> application classes to handle the triggering of workflows. 
          I created a custom BOR object for Contract (SD) with standard BOR inheritance and extended functionality. 
          For Bill of Materials (PP) and Out of Tolerance (PP), I created class-based workflows. 
          For every workflow, I created a template with approval tasks for My Inbox. 
          In the end, I developed a framework to dynamically replace the UI approval screen in <mark>My Inbox</mark> with standard <mark>Fiori</mark> extensibility tools in <mark>SAP Business Application Studio</mark>. 
          UI applications were stored in <mark>Git</mark> repositories.
      - layout: left
        title: Leave Request
        sub_title: Home Credit, China
        caption: Duration - 4 months (2021)
        description: | # this will include new lines to allow paragraphs
          Because of legal blockers, we could not use the standard SAP Leave Request application in China. 
          I had to develop a custom master-detail <mark>Fiori</mark> application using the <mark>SAPUI5</mark> SDK and with my own backend <mark>ABAP</mark> logic to validate data and update HR infotypes. 
          I built a simple <mark>SAP Business Workflow</mark> and integrated it into the <mark>My Inbox</mark> standard <mark>Fiori</mark> application.
      - layout: left
        title: My Travel Request V2
        sub_title: Home Credit, Philippines
        caption: Duration - 5 months (2020)
        description: | # this will include new lines to allow paragraphs          
          I participated in the development of <mark>SAP Business Workflow</mark> for <mark>Fiori</mark> applications Travel Request V2 and Travel Expense V2. I built custom BOR objects with inheritance from standard objects and designed and developed workflow templates.          
          The workflow template was robust because it consisted of 9 levels of approvers based on multiple conditions such as cost center, budget, and other parameters. The workflow template logic was supported by application <mark>ABAP</mark> classes.
          In the UI part, I had to extend standard <mark>Fiori</mark> applications using the standard extensibility concept in <mark>SAP WebIDE</mark>. For workflow approval, I created custom UI approval screens in <mark>My Inbox</mark>. In the end, I created user roles, assigned authorizations, 
          and registered applications into <mark>Fiori</mark> Launchpad .
      - layout: left
        title: USSPA Service Orders Planner
        sub_title: Versino CZ, s.r.o., Czech Republic
        caption: Duration - 4 months (2020)
        description: | # this will include new lines to allow paragraphs
          I designed and developed a custom <mark>SAPUI5</mark> application for planning services. The application consisted of an interactive map with tags, a list of orders, and a calendar. Apart from the <mark>SAPUI5</mark> SDK, I used custom <mark>JavaScript</mark> to meet customer requirements.
      - layout: left
        title: Trip Logbook
        sub_title: DHL Information Services s.r.o., Czech Republic
        caption: Duration - 4 months (2018)
        description: | # this will include new lines to allow paragraphs          
          As a full-time employee, I developed a custom master-detail <mark>Fiori</mark> application. The purpose of the application was to manage company car bookings and track journey details. The application UI layout was dynamically changing based on customization in SAP.
          The application was assigned to users in the <mark>Fiori</mark> Launchpad.
      - layout: left
        title: Company Website www.consit.cz
        sub_title: CONSIT s.r.o., Czech Republic
        caption: Duration - 4 months (2018)
        description: | # this will include new lines to allow paragraphs
          As a full-time employee, I developed the company website using <mark>HTML</mark> and <mark>JavaScript</mark> with content CMS integration from https://www.couchcms.com .
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: EmbedIT s.r.o., Czech Republic
        link: https://www.embedit.com
        sub_title: Senior SAP Software Engineer
        caption: February 2019 - Present
        description: | # this will include new lines to allow paragraphs           
          As an SAP software engineer, I design and develop business solutions for end customers. My largest projects have included development in <mark>ABAP</mark>, <mark>SAPUI5</mark>, and <mark>SAP Business Workflow</mark>.
          Apart from working on projects, I support business-as-usual operations by analyzing issues, extending core solutions, and implementing enhancements.
      - layout: left
        title: Heidelberg Materials, Germany
        link: https://www.heidelbergmaterials.com
        sub_title: Senior SAP Software Engineer
        caption: September 2021 - Present
        description: | # this will include new lines to allow paragraphs           
          I deliver software solutions for a German customer, primarily in the areas of <mark>SAP Business Workflow</mark>, custom <mark>ABAP</mark> business logic, and <mark>Fiori</mark> application development.
          I participated in the transformation from the old ERP system to S4 HANA. Apart from developing new solutions, I support my projects, extend solutions, and analyze issues.
      - layout: left
        title: DHL Information Services s.r.o., Czech Republic
        link: https://group.dhl.com/
        sub_title: SAP Software Engineer L3
        caption: February 2018 - January 2019
        description: | # this will include new lines to allow paragraphs           
           As a full-time employee, I supported business operations by fixing issues, enhancing existing solutions, and developing new applications using <mark>SAPUI5</mark> SDK and <mark>ABAP</mark>.           
           I had the opportunity to travel to Kuala Lumpur, Malaysia, to train developers in the areas of <mark>Fiori</mark> and <mark>SAPUI5</mark>.              
      - layout: left
        title: CONSIT s.r.o., Czech Republic
        link: https://www.consit.cz
        sub_title: SAP Fiori FrontEnd Developer
        caption: June 2016 - January 2018
        description: | # this will include new lines to allow paragraphs
           As a full-time employee, I designed and developed internal HR applications for company employees. I worked with <mark>SAPUI5</mark> SDK, <mark>JavaScript</mark>, and <mark>ABAP</mark>. 
           I also developed the company website. In this company, I had the opportunity to work with SAP for the first time.
      - layout: left
        title: Freelance
        sub_title: Web developer
        caption: January 2016 - May 2016
        description: | # this will include new lines to allow paragraphs
           I started my career as a webmaster and web developer. I became familiar with <mark>HTML</mark> <mark>JavaScript</mark> and <mark>Adobe Photoshop</mark> . 
           During this time, I worked on small tasks for multiple websites and developed my very first website, https://www.strednyliptov.sk      
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Žilina, Slovakia
        caption: 2010 - 2015
        sub_title: Services in IT
        description: | # this will include new lines to allow paragraphs
           I successfully graduated with a degree and wrote a diploma thesis on securing web forms in <mark>PHP</mark> .
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
           I was born in Slovakia but moved to Prague, the capital of Czechia, for new work opportunities. I love spending time with my family. I am a casual PS5 and PC gamer. I enjoy reading books and continuously improving myself in every possible way.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
